add gazebo_sfm_plugin to .rosinstall
voshch/arena-rosnav pull request #1
Opened 2023-09-28 12:55 UTC by TheZomb

the plugin wasn't in the .rosinstall. this should be fixed now

2023-10-05 11:47 UTC, voshch requested changes

2023-10-05 12:00 UTC, TheZomb commented on task_generator/task_generator/tasks/utils.py
ok didn't see the parameter.

2023-10-05 12:18 UTC, TheZomb reviewed
changed the manual call

2023-10-06 08:17 UTC, TheZomb commented
implemented change requested and added comments to dynamic_manager.py

2023-10-06 10:51 UTC, voshch approved these changes

2023-10-06 10:52 UTC, merged